### ISSUE TITLE
Parser failure with NPE

### ISSUE THREAD

**Issue by carstenlenz** [ghostbuster91/sttp-openapi-generator#192]
When trying to generate a client from the [spec of datatrans](https://api-reference.datatrans.ch/) the below exception is thrown - IMO when looking at the code there is a match on `Schema` but the val is null (https://github.com/ghostbuster91/sttp-openapi-generator/blob/master/parser/src/main/scala/io/github.ghostbuster91/sttp/client3/openapi/SafeOpenApi.scala#L261)

```[error] java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.get$ref()" because "<local7>" is null
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.SafeSchema$.apply(SafeOpenApi.scala:261)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.SafeMediaType.schema(SafeOpenApi.scala:151)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.OpenApiEnumFlattener$.$anonfun$collectOperationResponses$2(OpenApiEnumFlattener.scala:108)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.immutable.List.map(List.scala:305)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.OpenApiEnumFlattener$.collectOperationResponses(OpenApiEnumFlattener.scala:106)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.OpenApiEnumFlattener$.$anonfun$collectFromOperations$2(OpenApiEnumFlattener.scala:73)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:394)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.OpenApiEnumFlattener$.collectFromOperations(OpenApiEnumFlattener.scala:70)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.OpenApiEnumFlattener$.flatten(OpenApiEnumFlattener.scala:12)
[error] 	at io.github.ghostbuster91.sttp.client3.Codegen.$anonfun$generate$1(Codegen.scala:27)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.SafeOpenApiParser.$anonfun$parse$1(SafeOpenApiParser.scala:23)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at io.github.ghostbuster91.sttp.client3.openapi.SafeOpenApiParser.parse(SafeOpenApiParser.scala:23)
[error] 	at io.github.ghostbuster91.sttp.client3.Codegen.generate(Codegen.scala:30)
[error] 	at io.github.ghostbuster91.sttp.client3.SbtCodegenAdapter.processSingleFile(SbtCodegenAdapter.scala:30)
[error] 	at io.github.ghostbuster91.sttp.client3.SttpOpenApiCodegenPlugin$autoImport$.$anonfun$generateSources$3(SttpOpenApiCodegenPlugin.scala:67)
[error] 	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
[error] 	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
[error] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
[error] 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
[error] 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
[error] 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
[error] 	at io.github.ghostbuster91.sttp.client3.SttpOpenApiCodegenPlugin$autoImport$.$anonfun$generateSources$2(SttpOpenApiCodegenPlugin.scala:65)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error] 	at sbt.util.Difference.apply(Tracked.scala:414)
[error] 	at sbt.util.Difference.apply(Tracked.scala:394)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error] 	at sbt.util.Difference.apply(Tracked.scala:414)
[error] 	at sbt.util.Difference.apply(Tracked.scala:389)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error] 	at io.github.ghostbuster91.sttp.client3.SttpOpenApiCodegenPlugin$autoImport$.$anonfun$generateSources$1(SttpOpenApiCodegenPlugin.scala:76)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by carstenlenz** [comment]
Besides that the schema has some quirks (uses the `$` char in module names) the OpenAPI tools generator I also tried on this successfully outputs code.

**Comment by ghostbuster91** [comment]
Hi, thank you for the bug report. The more I have of them before reimplementing the parser the better.
